<?php
use Kernel\Security\Vulnerability\Xss;
use Kernel\Security\Vulnerability\Csrf;
use Kernel\Html\Attribute;
use Kernel\Html\Builder;
use Kernel\Html\Output;
use Kernel\Convert\Encoded;
use Kernel\Convert\Number;
use Kernel\Url\Location;
?>



<!-- 
Vue du composant Parametre.
Author: thiba
Version: 1.0
Categorie: Vue
 -->
<menu-parametre>
	<p>Le composant Parametre fonctionne !</p>
</menu-parametre>