<?php
use Kernel\Security\Vulnerability\Xss;
use Kernel\Security\Vulnerability\Csrf;
use Kernel\Html\Attribute;
use Kernel\Html\Builder;
use Kernel\Html\Output;
use Kernel\Convert\Encoded;
use Kernel\Convert\Number;
use Kernel\Url\Location;
?>



<!-- 
Vue du composant Scanner.
Author: thiba
Version: 1.0
Categorie: Vue
 -->
<menu-scanner>
	<div>		
		<video></video>
		<div id="barre"></div>
		<canvas></canvas>
	</div>
	<button class="button" onclick="menu_scanner.scanManually()">Entrer manuellement</button>
</menu-scanner>