<?php
use Kernel\Security\Vulnerability\Xss;
use Kernel\Security\Vulnerability\Csrf;
use Kernel\Html\Attribute;
use Kernel\Html\Builder;
use Kernel\Html\Output;
use Kernel\Convert\Encoded;
use Kernel\Convert\Number;
use Kernel\Url\Location;
?>



<!-- 
Vue du composant Accueil.
Author: thiba
Version: 1.0
Categorie: Vue
 -->
<accueil>
	<button onclick="accueil.refresh()">Actualiser</button>
	<p>Le composant Accueil fonctionne !</p>
</accueil>